### ISSUE TITLE
podcasts are not shown

### ISSUE THREAD

**Issue by estefi-prieto** [Cambalab/ns-vue-radio#166]
when install the the application build and go to the podcasts section, the app show an empty screen. The podcast section should show a podcast list

**Comment by sgobotta** [comment]
This could be happening because:

+   The component is not properly hitting the API
+   It's probably getting a 2xx status from the API but not retrieving data
+   It's probably getting a 2xx status from the API but the response is not correctly parsed

We discovered the first one is happening, though we'll have to deal with the third problem: the response is not correctly parsed.

I propose we fix the endpoints with the `appName` attribute and then handle the responses problem described in #151
