### ISSUE TITLE
Translate nativescript-firebase-plugin installation guide

### ISSUE THREAD

**Issue by FacundoMainere** [Cambalab/ns-vue-radio#4]
[guia-plugin-firebase.tar.gz](https://github.com/Cambalab/ns-vue-radio/files/2496376/guia-plugin-firebase.tar.gz)

and add it to the docs/

**Comment by Feyn-Man** [comment]
Hi! I've translated the markdown in the folder that you linked to italian, I have to commit it in a new folder named docs in the root?

**Comment by FacundoMainere** [comment]
Yes, exactly. Make a subfolder for your language like docs/Lang

Thank you!

**Comment by Feyn-Man** [comment]
I created a docs folder with Italian subfolder in which there are the 2 translation in italian for this issue and for  #3. I left the images folder that you passed in the zip file above in this subfolder along with the translated file. I think that a better solution is to put the images required from the guide in an images folder inside docs or directly in the root folder and change the images  path  into the markdown files to this folder, so every translation refers to one folder of images instead of copying multiple times the same things. 
If you agree with this change I can make this changes for the files that I've uploaded and push it to the repo.

**Comment by FacundoMainere** [comment]
I agree thats better to avoid repetition. But i would keep it as you pushed it so if someone wants to make localized images in your language they can put them in there.

I will make a separate issue for this though.

Thanks a lot for your contributions.
